apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfsserver-pv
  namespace: rook-nfs
  labels:
    volume_name: nfsserver-pv
spec:
  storageClassName: nfsstorageclass
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
    - ReadWriteOnce
  hostPath:
    path: "/var/nfsservercontainer"
  persistentVolumeReclaimPolicy: Retain