apiVersion: v1
kind: Service
metadata:
  name: phpdemo-service
  namespace: phpdemo
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: phpdemo