
name: CI

on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Building PHP Demo
        env :
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          cd phpsample
          docker build -t albertoclarit/phpdemo:1.0.3  .
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          docker push albertoclarit/phpdemo

